version: "3.10"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
     API_ID: # Your API HASH from my.telegram.org
     API_HASH: # Your API ID from my.telegram.org
     BOT_TOKEN: # Bot token, get it from @BotFather
     DATABASE_URL: #Your mongodb url obtained from mongodb.com  
     OWNER_ID: #Your telegram I'd use this bot @UploadLinkToFileBot and use /info
     BOT_USERNAME: #Your Bot Username Without @  
     DEF_THUMB_NAIL_VID_S: #Add your thumbnail pic from @vTelegraphBot
     UPDATES_CHANNEL: #Your Update channel id or skip
     LOG_CHANNEL: #Your Any Own Private Channel ID Where Your Bot As Admin With Full Permission
